apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-ctenorio
  namespace: ctenorio
spec:
  path: /
  to:
    kind: Service
    name: frontend-frontend-service
  port:
    targetPort: 8093
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAwY627CEhGmswoRpnaJZK4v+7NV5/NvefoYhljl0SdQRWXK69
      AP9F88Lnv/+YUForDLmHXlMGyNfi958F+foKY004ZhUkBRm5xhA2pFJO5MYlXHfV
      5oAaMnaDBKCto+A1JsWKXiqguhyG1urwG4BBZLiFCqBjot27m8Kpg2KdRMVo7cAH
      NxZNUeYmcYsrrVwoTs03SRBmC8QhVD4I15//cToQ05KucZFBwDP7qMuKFiVWSgD2
      Wa6Ph/QM7qV5o4jtTk4OszdTHc+QIqZ4grz9WAn1CM4sUVfNowWYytcRxuJb+tEU
      483eDL5QWfcc4NwWYhLTBmQ4U4pNJ/BvpXz9RwIDAQABAoIBAQCpqtheFIxYBC4U
      inirDVOHuHP6TGNnY5jimBWtvZg4Sx0JEYNMJHjFPMy5WOvDQ8cI2Hj5Df6cf+HM
      /fDXN39znHUbxtxUPEDEheHgGOZfU/HcJI+0BgbwxUIEBHUxeZAd9HteIC/T9L2e
      F0NyV/L6v2Sf9Ahi88tItlKxgPgrFvqg2xxKWw04V6BQLQvKyKXuQMOxWulcRrO9
      OMk5fUVVNocbkU987oFFgCR89fbxdU05uNVnmTF2D7nZcgLr0xOaTVBw+KkklWwh
      wzZ4b2G15vBnEc0W4Ur67wvvl7QfAYNsb9TFM4sN+UoVOk7vvSjLkuVTsbr1pdD4
      rzo2ufPBAoGBAOGkfpFb8NcMs3vveHvrmDG+NHZVDPyzHVbJ7F1DwV8NDOJsdiV8
      4NYiNf1itIJbqR98AD48fPRkRPcMKV9ubtfx0aH3wKEtPEgje965yE5EUDb53Lsz
      sJ9Qdb9jL8tF76snhbyRO1cbxCLUa+RsIWXT1Tr6byX2WMnovmS5at2tAoGBANuZ
      KBcukcR4cMPI2WpiK0XIgEoWfiQeSvUo53D1oKw3RsIpQer26Ip4zaS8HW4Cg6KT
      8C6BKV3BCT5pwgcJnkZbBTM8sEujONW+SXjmVzW84VIxA60KMhBJZBOXVh7Lt0CA
      pNsZPxH31plnb5vx6ZoqFZdN6c/8uNhHJPtjVf1DAoGAHn2z/MCH0weMWXsKtPQp
      JM+nFzZ3As7RcCDpJ9E4GDgTPaWacYZme4kz8oGcEuGAARkoj0BtQjkqeJfUH2k0
      4Ul0IobwKNeMBdOFsZs5Tho9HLC2+zUI8P5Wav5kPvu8X0x/7fNSKXs/DdXWno9e
      E/yEG+wriN25Mc+ZqtLDdiECgYAHUWtMmnixG3Jmk+Lq8KqQgMYFsgoyGfBViy9r
      TEQ2eQEap1VTBzdope30d3BjoiHQ4S0334YJYc11DwEwStnDbnUV6AfX/XB/bv/z
      z3lIiSrZGlkNAzH36Po0zO5JyHAq7h6QTp8Tcjbslc3aXI10XcKqcCZCkCF406Yf
      2oebEQKBgFqq2aPeYEoeVMQWIHozyr82Zo24RpLkx/ckMQdUETyoKHKGUW0G1fgj
      LBQ3ClC4uQaXGB7Tkdxgt1oZ67Gdf8Y4TaJGlfCwrU6aj4F2qcW39cG+sydDQ/di
      lEAuV2c4IE3yU5X47JwaRv6ZxfHLH9KaszmBv3evpfcbfAl9YccC
      -----END RSA PRIVATE KEY-----

    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIEvzCCAqegAwIBAgIUBGUwCHU6Ti0ZRLI8W/X5oUhbHIkwDQYJKoZIhvcNAQEL
      BQAwYTELMAkGA1UEBhMCRVMxDzANBgNVBAgMBlRvbGVkbzERMA8GA1UEBwwIVGFs
      YXZlcmExDzANBgNVBAoMBlN0ZW1kbzELMAkGA1UECwwCSUQxEDAOBgNVBAMMB2Rl
      ZmF1bHQwHhcNMjUwMTEwMTIxNTUwWhcNMjYwMTEwMTIxNTUwWjBhMQswCQYDVQQG
      EwJFUzEPMA0GA1UECAwGVG9sZWRvMREwDwYDVQQHDAhUYWxhdmVyYTEPMA0GA1UE
      CgwGU3RlbWRvMQswCQYDVQQLDAJJRDEQMA4GA1UEAwwHZGVmYXVsdDCCASIwDQYJ
      KoZIhvcNAQEBBQADggEPADCCAQoCggEBAMGOtuwhIRprMKEaZ2iWSuL/uzVefzb3
      n6GIZY5dEnUEVlyuvQD/RfPC57//mFBaKwy5h15TBsjX4vefBfn6CmNNOGYVJAUZ
      ucYQNqRSTuTGJVx31eaAGjJ2gwSgraPgNSbFil4qoLochtbq8BuAQWS4hQqgY6Ld
      u5vCqYNinUTFaO3ABzcWTVHmJnGLK61cKE7NN0kQZgvEIVQ+CNef/3E6ENOSrnGR
      QcAz+6jLihYlVkoA9lmuj4f0DO6leaOI7U5ODrM3Ux3PkCKmeIK8/VgJ9QjOLFFX
      zaMFmMrXEcbiW/rRFOPN3gy+UFn3HODcFmIS0wZkOFOKTSfwb6V8/UcCAwEAAaNv
      MG0wawYDVR0RBGQwYoJgZXotaWJtLW9wZW5zaGlmdC12cGMtbGttYy1iOWJlOWVk
      NmFlMzNkNzQzODE1MjQ1ZDBiNzczZWJjNy0wMDAwLmV1LWVzLmNvbnRhaW5lcnMu
      YXBwZG9tYWluLmNsb3VkMA0GCSqGSIb3DQEBCwUAA4ICAQCBIr/Xg8bgRbcmCv/r
      h3y05bpmF/kvPsj0hqUSwEPy/YRo+Bhpwd0LBkUgbdwmcMm0k2TcD8N4IHlEOT5d
      RZPPnM0u403vKSMKYmvPCuJhp2JgoQTzafxwV/lEbPB2EPqmnTEN4GFZl9N2/mg8
      +Le/mMBfDH8YgzNSM2pJ5WPN2HXn8EdF+JNNIywryVV+BzWiZYw7Gup3k/FkdVQ9
      i5a2nXKMYDfsLfvbEte8Q+JTJzaIg99ezFSUguyk9uTAvKJdP2FVLgmJIAjR+A0G
      m+pPMUxuvzU2W/3F1jPQIjmsGhaUyP/jPDDrE84v+DB7ss0wUKN2LRJmvEnGuUKN
      ZMtCU9xqWt50QYAiVXYIwr7KDR//g/wFOZEwt3UqOMoqwkBHQt5ibTY04wqOKoQB
      0DzEX/zoGaLKZCL8yEZpLxFl+qocVGiIXSsH+MKOkFK05luR981zfj9FxkOZmpiM
      3L/fzqfEKeCBqdz/Uh9kmp7irsl23GVzAM/L4NCHmKLmP5a5VxTmw36stxTZOw5E
      KvtzJqsCikGvOnGaIFt1xywwvIBhnXO1mYhIUfn3WrrajMC3tgBkCheklHbnsMyT
      9lEndZJi7AmHQbyy0c22aOtR6Y+Y1nPKY5z5P1xc5x+RiZJENN0LeGodmE7Wk1Fk
      zXwY4j7rqTKnvYR4gawrCWqviA==
      -----END CERTIFICATE-----

    caCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIFSTCCAzECFFayzFfCcBraJ2D891a1ta5EiWHUMA0GCSqGSIb3DQEBCwUAMGEx
      CzAJBgNVBAYTAkVTMQ8wDQYDVQQIDAZUb2xlZG8xETAPBgNVBAcMCFRhbGF2ZXJh
      MQ8wDQYDVQQKDAZTdGVtZG8xCzAJBgNVBAsMAklEMRAwDgYDVQQDDAdkZWZhdWx0
      MB4XDTI1MDExMDEyMTUxMVoXDTI2MDExMDEyMTUxMVowYTELMAkGA1UEBhMCRVMx
      DzANBgNVBAgMBlRvbGVkbzERMA8GA1UEBwwIVGFsYXZlcmExDzANBgNVBAoMBlN0
      ZW1kbzELMAkGA1UECwwCSUQxEDAOBgNVBAMMB2RlZmF1bHQwggIiMA0GCSqGSIb3
      DQEBAQUAA4ICDwAwggIKAoICAQCs69N0Npg3BBNYdKRLG3qYDj0PayBHfMas1xkX
      JCOXAgaleY6/w1duIkHW/FCtAhI+Lvq3L9zGmktq1T/u3BZQnJok92BxI/gZHEYP
      ExtI1eXvcZPiVYvL5BM7yvrXtZD6E1La2Gh3854Ej22J/SCcfhVWH53Xr5l5z5aU
      4xdWoYV8EcXOMWUtaSJhfVcjSPrWNjU7KoOY1v0zS2AAwZaTuNmx42mRU6Vedfto
      TVZ4U6AxWH9AibT0+ThrcEJcGutrBxtw4Env4EpJsyj9vzu/cPdBsuMLGnps7lh6
      gg0GYjiOHpTrINE3S9dBO2GzggQbvkYB2p4xcI3rdzLtJOydhtdPr0LHqDCui/Q4
      QFcAtWA0OUP2nbldLb4alRTQ/Ksa6WCO7Ys+6Jy0+NqoevqCrHGOKdiRwMXe4bU9
      RZbub7P01tZWjFPj8qfczG+OnmT+HzF2fJ4FAMZyxj7XHNp2GP5Hl1iTJziIPvVv
      rkL7LfHwUfpfDiE2qrQX4oIoUErD9/5v+Ij5HIz58zavrw0NvZl2YEE5NqkkIM6c
      FrzQDUoGC5YWcyGL4b7awj+jS7BsHXAefhnPyx/Hr/7VYJeXw55U6oviFjvrveCg
      XXaLrkx/Uz0zDcVbqxfa1Uie2jsdtmjMTLWIcl8TtSVcqJvt0hWOcjLd13zOvMTg
      d4UADQIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQBhuVHktO5eLpJB20zwLzujF/t/
      ZXe38IuDm0XETEz2bZGUsNSTQ0amU7Zf3DWIpmkIWLv+eXkk+Tm9f0aDqSNWXF1F
      Gs5SnhdVcnq6tWE7SJoTYfqzrIj/ZCWffqDIb6y32tzxy1UMxMJkTiGxlPvl5QJp
      Zzm2m0n48H2pI1EopMyAVm+ckfwctvBcaC+GyocPGxw/IpHh6k17xh4thMiMY9tX
      mdVQJUha0butI92Slitb0faELZrBE13SvQFTANpgwadgRsrXrW2F4uiLx6FxmqS7
      OEy3AiA+tYaMLvwYZy8tTgpEfzlurjKk3pGoESaw5thVblAPcn/VOc5i5nbCZv/X
      PHkRr7tphpT/kXG+gmPIhrK+4A1R/6o8tmlZ+mkDTKF/ig0F6TMxUsKhtxmn1E3C
      Gj1gbbcGG4cU1cFNxj3YCTWI9qRX2rloXLXkpztVuWKacVi8Q0Q9w06zkEjdQoA9
      dQh506J1sS1/NF6ECPwsqI3lXr/KvuU1XDgnj6e1I9lpZ4ssn1I5OUvaz+GOfssN
      y0VxJODIr+gRutOPAc+yO3BJzlsilP+PR8rANZVVXdcBpyfcJ85Ur468oIWLYMPt
      RSNxH//A8qQXPWYh5r/eWSPgLRF2oMLJ0wXxgZUjjsMhduAmXahlcGgmf1H20rxW
      STOpUTQ709HEEXQFZQ==
      -----END CERTIFICATE-----

   
