apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-ctenorio
  namespace: ctenorio
spec:
  path: /
  to:
    kind: Service
    name: frontend-frontend-service
  port:
    targetPort: 8093
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    key: |
      -----BEGIN RSA PRIVATE KEY-----
     
      -----END RSA PRIVATE KEY-----

    certificate: |
      -----BEGIN CERTIFICATE-----
 
      -----END CERTIFICATE-----

    caCertificate: |
      -----BEGIN CERTIFICATE-----

      -----END CERTIFICATE-----

   
