apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  SPRING_DB_PASSWORD: {{ .Values.backend.SPRING_DB_PASSWORD | b64enc }}
