- name: Configuraci칩n e instalaci칩n de PostgreSQL
  hosts: postgresql_servers
  become: true

  vars:
    postgres_db: "{{ lookup('env', 'POSTGRES_DB') }}"
    postgres_user: "{{ lookup('env', 'POSTGRES_USER') }}"
    postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"

  tasks:
    - name: Agregar el repositorio oficial de PostgreSQL 16
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main"
        state: present
        filename: "pgdg"

    - name: Importar la clave GPG del repositorio de PostgreSQL
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Actualizar el repositorio de paquetes
      apt:
        update_cache: yes

    - name: Instalar PostgreSQL 16 y los paquetes necesarios
      apt:
        name:
          - postgresql-16
          - postgresql-client-16
          - python3-psycopg2
        state: present

    - name: Asegurarse de que PostgreSQL 16 est치 en ejecuci칩n
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Crear una base de datos
      become_user: post
