- name: Configuraci칩n e instalaci칩n de PostgreSQL
  hosts: postgresql_servers
  become: true

  vars_files:
    - variables.yaml

  tasks:
    - name: Actualizar el repositorio de paquetes
      apt:
        update_cache: yes
 
    - name: Instalar PosgreSQL y los paquetes necesarios
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
        state: present
        update_cache: yes
 
    - name: Asegurarse de que PostgreSQL est치 en ejecuci칩n
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Crear una base de datos
      become: true
      become_user: postgres
      postgresql_db:
        name: "{{ postgres_db }}"
        owner: "postgres"
        encoding: "UTF8"
        state: present

    - name: Crear usuario PostgreSQL
      become: true
      become_user: postgres
      postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        role_attr_flags: SUPERUSER
        state: present

    - name: Cambiar el propietario de la base de datos
      become: true
      become_user: postgres
      shell: |
        psql -c "ALTER DATABASE {{ postgres_db }} OWNER TO {{ postgres_user }};"

    - name: Configurar listen_addresses = '*' en postgresql.conf
      become: yes
      become_user: root
      lineinfile:
        path: "/etc/postgresql/16/main/postgresql.conf"  
        regexp: '^#?listen_addresses ='
        line: "listen_addresses = '*'"
        state: present

    - name: Configurar acceso en pg_hba.conf
      become: yes
      become_user: root
      lineinfile:
        path: "/etc/postgresql/16/main/pg_hba.conf"
        regexp: '^host\s+all\s+all\s+0.0.0.0/0\s+md5'
        line: "host    all             all             0.0.0.0/0               md5"
        state: present

    - name: Configurar acceso en pg_hba.conf para myuser y la base de datos rrhh
      become: yes
      become_user: root
      lineinfile:
        path: "/etc/postgresql/16/main/pg_hba.conf"
        regexp: '^host\s+rrhh\s+myuser\s+127\.0\.0\.1/32\s+md5'
        line: "host    rrhh            myuser          127.0.0.1/32            md5"
        state: present
  
      - name: Reiniciar PostgreSQL 16
        service:
          name: postgresql
          state: restarted
