- name: Configuraci칩n e instalaci칩n de PostgreSQL
  hosts: postgresql_servers
  become: true

  vars:
    postgres_db: "{{ lookup('env', 'POSTGRES_DB') }}"
    postgres_user: "{{ lookup('env', 'POSTGRES_USER') }}"
    postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"

  tasks:
    - name: Agregar el repositorio oficial de PostgreSQL 16
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main"
        state: present
        filename: "pgdg"

    - name: Importar la clave GPG del repositorio de PostgreSQL
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Actualizar el repositorio de paquetes
      apt:
        update_cache: yes

    - name: Instalar PostgreSQL 16 y los paquetes necesarios
      apt:
        name:
          - postgresql-16
          - postgresql-client-16
          - python3-psycopg2
        state: present

    - name: Asegurarse de que PostgreSQL 16 est치 en ejecuci칩n
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Crear una base de datos
      become_user: postgres
      community.postgresql.postgresql_db:
        name: "{{ postgres_db }}"
        owner: "postgres"
        encoding: "UTF8"
        state: present

    - name: Crear usuario PostgreSQL
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        role_attr_flags: SUPERUSER
        state: present

    - name: Cambiar el propietario de la base de datos
      become_user: postgres
      shell: |
        psql -c "ALTER DATABASE {{ postgres_db }} OWNER TO {{ postgres_user }};"

    - name: Configurar listen_addresses = '*' en postgresql.conf
      lineinfile:
        path: "/etc/postgresql/16/main/postgresql.conf"
        regexp: '^#?listen_addresses ='
        line: "listen_addresses = '*'"
        state: present

    - name: Configurar acceso en pg_hba.conf
      lineinfile:
        path: "/etc/postgresql/16/main/pg_hba.conf"
        regexp: '^host\s+all\s+all\s+0.0.0.0/0\s+md5'
        line: "host    all             all             0.0.0.0/0               md5"
        state: present

    - name: Reiniciar PostgreSQL 16
      service:
        name: postgresql
        state: restarted
