- hosts: postgresql_servers
  become: yes
  vars:
    postgresql_version: "14"
    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: md5 }
      - { type: local, database: all, user: all, auth_method: md5 }
      - { type: host, database: all, user: "{{ lookup('env', 'DB_USER') }}", address: '127.0.0.1/32', auth_method: md5 }
      - { type: host, database: all, user: "{{ lookup('env', 'DB_USER') }}", address: '::1/128', auth_method: md5 }
      - { type: host, database: "{{ lookup('env', 'DB_NAME') }}", user: "{{ lookup('env', 'DB_USER') }}", address: '192.168.1.0/24', auth_method: md5 }
      - { type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5 }
    postgresql_global_config_options:
      - option: listen_addresses
        value: '*'
      - option: log_directory
        value: '/var/log/postgresql'
    postgresql_databases:
      - name: "{{ lookup('env', 'DB_NAME') }}"
        state: present
    postgresql_users:
      - name: "{{ lookup('env', 'DB_USER') }}"
        password: "{{ lookup('env', 'PGPASSWORD') }}"
        encrypted: yes
        state: present
    
  roles:
    - geerlingguy.postgresql

