name: Empaquetar y subir el chart a Harbor

on:
  workflow_dispatch:
    inputs:
      chart:
        description: "Selecciona el chart a empaquetar y subir"
        required: true
        type: choice
        options:
          - frontend
          - backend
        default: frontend

jobs:
  package-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Package Helm Chart
      run: |
        helm package ${{ github.event.inputs.chart }}
      working-directory: ./charts

    - name: List packaged charts
      run: |
        ls -l ./charts

    - name: Push Helm Chart to Harbor
      run: |
        CHART_FILE=$(ls ./charts/${{ github.event.inputs.chart }}-*.tgz)
        helm push $CHART_FILE oci://uk.icr.io/ctenorio-cr
      working-directory: ./charts
