name: Empaquetar y subir el chart a Harbor

on:
  workflow_dispatch:
      inputs:
        chart:
          description: "Selecciona el chart a empaquetar y subir"
          required: true
          type: choice
          options:
            - frontend
            - backend
          default: frontend

jobs:
  package-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash


    - name: Package Helm Charts
      run: |
        helm package ${{ github.event.inputs.chart }} 
      working-directory: ./charts

    - name: Push Helm Charts to Harbor
      run: |
           helm push ${{ github.event.inputs.chart }}-${{ steps.version.outputs.version }}.tgz oci://uk.icr.io/ctenorio-cr
      working-directory: ./charts
