name: Ansible

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  ansible:
    name: Run Ansible Playbook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible and dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass python3 python3-pip
          pip3 install psycopg2-binary

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.IP_PUBLICA}} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
        
      - name: Create inventory.ini file
        run: |
          echo "[postgresql_servers]" > inventory.ini
          echo "${{ secrets.IP_PUBLICA }} ansible_user=root" >> inventory.ini

        working-directory: ./ansible


      - name: Execute playbook
        run: |
          ansible-playbook -i inventory.ini install-postgresql.yaml
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
        working-directory: ./ansible
